// <auto-generated />
namespace MyShop.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migracao01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracao01));
        
        string IMigrationMetadata.Id
        {
            get { return "201811140102085_migracao01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
